<a href="https://colab.research.google.com/github/yankeesong/MLE/blob/main/torch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

Lots of syntaxes are similar to pandas/numpy

## Data manipulation

In [ ]:
a = torch.arange(12)
a.numel()
a.reshape(3,4)
torch.zeros((2,3,4))
torch.ones((2,3,4))
torch.randn(3,4)

## Data Preprocessing

In [ ]:
X = pd.read_csv(filename)
X = torch.tensor(X.values)

19

## Linear Algebra

In [5]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])
a @ b
torch.mm(a,b)

tensor([[19, 22],
        [43, 50]])


tensor([[19, 22],
        [43, 50]])

## Automatic Differentiation

In [4]:
# Simple gradient
x = torch.arange(4.0)
x.requires_grad_(True)
y = 2 * torch.dot(x, x)
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [5]:
# Reset
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [8]:
# Jacobian for vector valued y
x.grad.zero_()
y = x * x
y.backward(gradient=torch.ones(len(y)))  # Faster: y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [7]:
# For isolating one variable (partial derivative)
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)